- name: Ensure directory exists
  file:
    path: "/tmp/keystore/"
    state: directory
    owner: "{{ project.uid }}"
    group: "{{ project.gid }}"
    mode: 0775

- name: Create Elastic Keystore 
  shell: docker run --rm --user 1000:1000 --name elk-keystore -d -w /usr/share/elasticsearch -v $PWD/shell/elastic/setup_keystore.sh:/usr/share/elasticsearch/setup_keystore.sh -v /tmp/keystore/:/tmp/keystore/ {{ elastic.image_name }}:{{ elastic.image_tag }} bash -c "./setup_keystore.sh"
  register: result
  retries: 3
  delay: 1

- name: Wait for 10 seconds to get generated keystores ready
  pause:
    seconds: 10

- name: Copy Keystore file
  copy:
    src: "/tmp/keystore/elasticsearch.keystore"
    remote_src: yes
    dest: "{{ project.base_path }}/elasticsearch/config/elasticsearch.keystore"
    owner: "{{ project.uid }}"
    group: "{{ project.gid }}"
    mode: 0775
  retries: 3
  delay: 5  