- name: Ensure directory exists
  file:
    path: "/tmp/escert"
    state: directory
    owner: "{{ project.uid }}"
    group: "{{ project.gid }}"
    mode: 0775

- name: Create Elastic Certifcates 
  shell: docker run --rm -it -d -v /tmp/escert/:/tmp/escert/ {{ elastic.image_name }}:{{ elastic.image_tag }} ./bin/elasticsearch-certutil ca --out /tmp/escert/{{ elastic.cert }} -s --pass ""
  register: result
  retries: 3
  delay: 1

- name: Ensure directory exists
  file:
    path: "{{ item.src }}"
    state: directory
    owner: "{{ project.uid }}"
    group: "{{ project.gid }}"
    mode: 0775
  with_items:
    - "{{ elastic_config }}"


- name: Copy Cert file
  copy:
    src: "/tmp/escert/{{ elastic.cert }}"
    remote_src: yes
    dest: "{{ item.src }}/{{ elastic.cert }}"
    owner: "{{ project.uid }}"
    group: "{{ project.gid }}"
    mode: 0775
  with_items:
    - "{{ elastic_config }}"
