password:
  elastic: "VFNyxcx7thzWwWq6o1Qf"
  jenkins: ""
  keycloak_admin: ""
  deployment: ""
  docker_user: "x2GROUPIT2x"
  main: "x2GROUPIT2x"
  beats_system: "x2BEATS2x"
  kafka_admin: "development"
  kafka_ui: "development"